Yubikey:
  - Serial: 123456
  - Owner: CowboyAI
  - Config:
    - PIV:
      - PIN: 123456
      - PUK: 12345678
      - Management Key: 0x010203040506070801020304050607080102030405060708
    - FIDO2:
      - PIN:
        - value:
        - minlength: 6 # 4 to 63
        - utf: false # this is fido1
      - credentials: # passkeys and passwords
        - git:
          - signing: # git signing key
          - ssh: # ssh credentials
      - fingerprints: # fingerprints
        - left-thumb: 
    - OAUTH:
      - 
    - OpenPGP:
      - name: cowboyai
      - email: support@thecowboy.ai
      - comment: Comments are disabled
    - OTP: